# Generated by Django 4.1.3 on 2023-03-12 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_cata_itea_loca_subd_delete_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cata',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Itea',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Subd',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='Loca',
            new_name='Subdivision',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='sub',
            new_name='loc',
        ),
        migrations.RenameField(
            model_name='subdivision',
            old_name='loc',
            new_name='sub',
        ),
    ]
