# Generated by Django 4.1.3 on 2023-03-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_rename_cata_department_rename_itea_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_authorized',
            field=models.BooleanField(default=False, verbose_name='is authorized'),
        ),
    ]
