# Generated by Django 4.1.3 on 2023-03-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_user_is_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_authorized',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
